services:
  - type: web
    name: aegis
    runtime: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/eabrahym75/Aegis.git
    branch: main
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: PYTHON_PATH
        value: /usr/bin/python3
